on: push
name: on push
jobs:
  gitHubActionForPytest:
    name: GitHub Action for pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run pytest
      with:
          args: python setup.py develop && pytest
