on: push
name: on push
jobs:
  gitHubActionForPytest:
    name: GitHub Action for pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install packages
      run: |
          sudo python3 -m pip install --upgrade pip
          sudo apt-get install -y python3-setuptools
          sudo python3 -m pip install --upgrade setuptools
          sudo pip install -r requirements.txt
    - name: Run pytest
      run: |
          sudo python setup.py install
          pytest
